#!/bin/sh
#
# xinitrc runs automatically when you run startx/xinit

# set some fallbacks to default xorx settings just in case
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Call everything in xprofile before starting wm
[[ -f "$XDG_CONFIG_HOME/X11/xprofile" ]] && . "$XDG_CONFIG_HOME/X11/xprofile"

# Start wm
exec bspwm
#exec i3
