#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit this file will also be sourced.

xrdb $XRESOURCES                        # Load Xresources
xsetroot -cursor_name left_ptr &        # Set the mouse cursor
unclutter &                             # Remove mouse when idle
iscmd remap && remap                    # Remaps the keyboard
xset +fp /home/chris/.local/share/fonts # Add to font path
xset fp rehash                          # Rehash font dir
#iscmd conf_display && conf_display      # Configure Xserver for monitors
