#
# ~/.config/bash/bashrc
#
# Configurations for bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Simple prompt
if [ -n "$SSH_CONNECTION" ]; then
	export PS1="\u@\h: \w \$ "
else
	export PS1="\w \$ "
fi
export PS2="> "

# Enable tab completion when starting a command with 'sudo'
[ "$PS1" ] && complete -cf sudo

# History settings
HISTFILE="${XDG_CONFIG_HOME:-$HOME/.config}/bash/bash_history"
HISTSIZE=1000
HISTFILESIZE=2000
HISTCONTROL=ignoreboth
shopt -s histappend

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc"
