#!/bin/sh
#
# bspwmrc --- Configuration script for BSPWM.
#
# This file is part of a custom set up for running bspwm.
# Other important settings are also defined in xinitrc and the sxhkd configs.


#####====---Essentials---====#####

# Determine the XrandR settings
iscmd conf_display && conf_display

# Set the workspaces per monitor.
bspc monitor "DP1" -d 1 2 3 4 5

#if [ "$(bspc query -M | wc -l)" -eq 2 ]; then
	#bspc monitor "eDP-1" -d 1 2 3 4 5
	#bspc monitor "DP-1" -d 1 2 3 4 5
	#bspc monitor "HDMI2" -d 6 7 8 9 0
    #bspc config borderless_monocle false
#else
	#bspc monitor -d 1 2 3 4 5 6 7 8 9 0
#fi


#####====---Visual Options---====#####

bspc config initial_polarity second_child
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config ignore_ewmh_focus false
bspc config single_monocle true
bspc config pointer_modifier shift
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer false
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config top_padding 22
bspc config top_monocle_padding 0
bspc config bottom_padding 0
bspc config bottom_monocle_padding 0
bspc config left_monocle_padding 0
bspc config right_monocle_padding 0
bspc config window_gap 10
bspc config border_width 2
bspc config split_ratio 0.50
bspc config border_radius 6
bspc config normal_border_color "#2E3440"
bspc config focused_border_color "#5c6370"
bspc config presel_feedback_color "#98c379"


#####====---Autostart---====#####

# Kill all running applications before starting
killall -9 sxhkd picom polybar

# Remap the custom keyboard layout
iscmd remap && remap

# The hotkey daemon that handles all custom key bindings.
iscmd sxhkd && sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc &

# Start polybar
iscmd polybar && $XDG_CONFIG_HOME/polybar/launch.sh &

# Start picom
iscmd picom && picom -b --config $XDG_CONFIG_HOME/picom/picom.conf &

# Set the wallpaper
feh --no-fehbg --bg-fill /home/chris/docs/photos/wallpapers/nord-mountains.png

#################################
