#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit this file will also be sourced.

xrdb $XRESOURCES                        # Load Xresources
xsetroot -cursor_name left_ptr &        # Set the mouse cursor
remap &                                 # Remaps the keyboard
unclutter &                             # Remove mouse when idle
#polybar main &                          # Start statusbar 
